"""Add MaintenanceLog

Revision ID: 0d47a9ab7e7c
Revises: 3d72397420ff
Create Date: 2026-07-30 15:36:43.840683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d47a9ab7e7c'
down_revision: Union[str, Sequence[str], None] = '3d72397420ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_current_site_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'sites', ['current_site_id'], ['site_id'])
    op.drop_constraint(op.f('assignments_asset_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'assets', ['asset_id'], ['asset_id'])
    op.alter_column('engine_events', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(op.f('qr_scan_logs_asset_id_fkey'), 'qr_scan_logs', type_='foreignkey')
    op.create_foreign_key(None, 'qr_scan_logs', 'assets', ['asset_id'], ['asset_id'])
    op.drop_constraint(op.f('rental_requests_site_id_fkey'), 'rental_requests', type_='foreignkey')
    op.create_foreign_key(None, 'rental_requests', 'sites', ['site_id'], ['site_id'])
    op.drop_constraint(op.f('rentals_asset_id_fkey'), 'rentals', type_='foreignkey')
    op.drop_constraint(op.f('rentals_site_id_fkey'), 'rentals', type_='foreignkey')
    op.create_foreign_key(None, 'rentals', 'assets', ['asset_id'], ['asset_id'])
    op.create_foreign_key(None, 'rentals', 'sites', ['site_id'], ['site_id'])
    op.alter_column('sensor_health', 'sensor_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('telemetry', 'telemetry_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetry', 'telemetry_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('sensor_health', 'sensor_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.create_foreign_key(op.f('rentals_site_id_fkey'), 'rentals', 'sites', ['site_id'], ['site_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('rentals_asset_id_fkey'), 'rentals', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rental_requests', type_='foreignkey')
    op.create_foreign_key(op.f('rental_requests_site_id_fkey'), 'rental_requests', 'sites', ['site_id'], ['site_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'qr_scan_logs', type_='foreignkey')
    op.create_foreign_key(op.f('qr_scan_logs_asset_id_fkey'), 'qr_scan_logs', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.alter_column('engine_events', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_asset_id_fkey'), 'assignments', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_current_site_id_fkey'), 'assets', 'sites', ['current_site_id'], ['site_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
