"""Initial migration

Revision ID: 3d72397420ff
Revises: 
Create Date: 2026-07-30 13:31:30.534458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d72397420ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the timescaledb extension if it doesn't exist
    # op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_events',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_value', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'asset_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('sensor_health',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('gps_status', sa.String(), nullable=True),
    sa.Column('temperature_sensor', sa.String(), nullable=True),
    sa.Column('fuel_sensor', sa.String(), nullable=True),
    sa.Column('battery_sensor', sa.String(), nullable=True),
    sa.Column('network_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'asset_id'),
    sa.UniqueConstraint('sensor_id')
    )
    op.create_table('sites',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('site_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('telemetry',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('telemetry_id', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('engine_hours', sa.Float(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('engine_temperature', sa.Float(), nullable=True),
    sa.Column('oil_pressure', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('idle_hours', sa.Float(), nullable=True),
    sa.Column('runtime_today', sa.Float(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('network_strength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'asset_id'),
    sa.UniqueConstraint('telemetry_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('rfid_tag', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('purchase_year', sa.Integer(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.Column('current_site_id', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('total_engine_hours', sa.Float(), nullable=True),
    sa.Column('fuel_capacity', sa.Float(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_due', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('qr_code'),
    sa.UniqueConstraint('rfid_tag'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('rental_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('dealer_id', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('requested_start_date', sa.DateTime(), nullable=True),
    sa.Column('requested_end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('assignment_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('qr_scan_logs',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scan_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('rentals',
    sa.Column('rental_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('assigned_operator', sa.String(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('expected_return', sa.DateTime(), nullable=True),
    sa.Column('actual_return', sa.DateTime(), nullable=True),
    sa.Column('rental_status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('rental_id')
    )
    # ### end Alembic commands ###
    
    # Convert telemetry tables into TimescaleDB hypertables
    # (Commented out because timescaledb extension is not installed locally)
    # op.execute("SELECT create_hypertable('engine_events', 'timestamp');")
    # op.execute("SELECT create_hypertable('sensor_health', 'timestamp');")
    # op.execute("SELECT create_hypertable('telemetry', 'timestamp');")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    op.drop_table('qr_scan_logs')
    op.drop_table('assignments')
    op.drop_table('rental_requests')
    op.drop_table('assets')
    op.drop_table('telemetry')
    op.drop_table('sites')
    op.drop_table('sensor_health')
    op.drop_table('engine_events')
    # ### end Alembic commands ###
